import { Loader2 } from 'lucide-react';
export function OverviewSkeleton({className='', error, retry}:{className?:string;error?:string;retry?:()=>void}) {
  return <div aria-busy={!error} className={`space-y-4 ${className}`}>
    <header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold tracking-tight text-slate-900">Airfare Intelligence Overview</h1><p className="mt-1 text-xs text-slate-600">Real-time domestic airfare collection status, route coverage, and market intelligence.</p></div><div className="flex gap-2"><button disabled className="rounded border px-3 py-2 text-xs text-slate-500">Refresh</button><button disabled className="rounded border px-3 py-2 text-xs text-slate-500">Generate Report</button></div></header>
    <div role={error?'alert':'status'} className="flex items-center gap-3 rounded-lg border border-blue-100 bg-blue-50 p-3 text-blue-900">{!error&&<Loader2 size={18} className="animate-spin motion-reduce:animate-none"/>}<div><p className="text-sm font-semibold">{error?'Unable to load live overview':'Preparing live intelligence…'}</p><p className="mt-1 text-xs">{error??'Resolving LIVE + IMPORTED observations'}</p></div>{retry&&<button onClick={retry} className="ml-auto rounded border border-blue-300 px-3 py-2 text-sm">Retry</button>}</div>
    {!error&&<><div aria-label="Loading filters" className="flex flex-wrap gap-3 rounded-lg border border-slate-200 bg-white p-4">{['Date range','Supported corridors','Sources','Compare','Booking window'].map(x=><div key={x} className="text-xs text-slate-600">{x}<div aria-hidden="true" className="mt-2 h-7 w-28 rounded bg-slate-100"/></div>)}</div>
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{['LIVE OBSERVATIONS','ACTIVE ROUTES','LATEST COLLECTION','VALIDATED FARES','ACTIVE ANOMALIES'].map(x=><div key={x} className="rounded-lg border border-slate-200 bg-white p-4"><p className="text-[10px] font-semibold text-slate-600">{x}</p><div aria-hidden="true" className="my-3 h-7 w-16 animate-pulse rounded bg-slate-100 motion-reduce:animate-none"/><div aria-hidden="true" className="h-3 w-24 rounded bg-slate-100"/></div>)}</div>
    <div className="grid gap-4 lg:grid-cols-2">{['Current Route Fare Snapshot','Observed Fare Range','Latest Live Observations','Route Activity'].map((x,i)=><section key={x} className="rounded-lg border border-slate-200 bg-white p-4"><h2 className="text-sm font-semibold">{x}</h2>{i<2?<div aria-hidden="true" className="mt-4 h-52 animate-pulse rounded bg-slate-100 motion-reduce:animate-none"/>:<div aria-hidden="true" className="mt-4 space-y-3">{[1,2,3,4].map(n=><div key={n} className="h-10 animate-pulse rounded bg-slate-100 motion-reduce:animate-none"/>)}</div>}</section>)}</div></>}
  </div>;
}
