from datetime import date, datetime
from decimal import Decimal
from typing import Any, Dict, List, Optional
from uuid import UUID
from pydantic import BaseModel, ConfigDict, Field

from app.core.enums import CabinClass, CollectionRunStatus, PipelineStatus, StepStatus, TriggerType


class SearchRequest(BaseModel):
    """Canonical search request model generated by the collection orchestrator."""
    origin: str = Field(..., min_length=3, max_length=3, description="3-letter IATA code, e.g. DEL")
    destination: str = Field(..., min_length=3, max_length=3, description="3-letter IATA code, e.g. BOM")
    departure_date: date
    booking_window_days: int = Field(..., ge=0, le=365)
    passengers: int = Field(1, ge=1, le=9)
    cabin: CabinClass = CabinClass.ECONOMY
    currency: str = "INR"
    max_results: int = Field(15, ge=1, le=20, description="Bounded maximum fare observations to collect (safety cap 20)")
    is_nonstop: Optional[bool] = Field(None, description="Filter for nonstop direct flights only")
    requested_at: datetime = Field(default_factory=datetime.utcnow)
    source_id: Optional[UUID] = None
    collection_run_id: Optional[UUID] = None


class CollectionRunCreate(BaseModel):
    source_id: Optional[UUID] = None
    run_type: str = "batch_search"
    routes_requested: int = 0
    searches_requested: int = 0
    trigger_type: TriggerType = TriggerType.SCHEDULED
    triggered_by: Optional[str] = None
    metadata: Optional[Dict[str, Any]] = None


class PipelineStepResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: UUID
    step_name: str
    status: StepStatus
    started_at: Optional[datetime]
    finished_at: Optional[datetime]
    records_input: int
    records_output: int
    records_failed: int
    duration_ms: Optional[int]
    message: Optional[str]


class PipelineRunDetail(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: UUID
    pipeline_type: str
    started_at: datetime
    finished_at: Optional[datetime]
    status: PipelineStatus
    records_input: int
    records_processed: int
    records_failed: int
    steps: List[PipelineStepResponse] = []


class CollectionRunDetail(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: UUID
    source_id: Optional[UUID]
    run_type: str
    started_at: datetime
    finished_at: Optional[datetime]
    status: CollectionRunStatus
    routes_requested: int
    searches_requested: int
    requests_successful: int
    requests_failed: int
    quotes_received: int
    quotes_validated: int
    quotes_rejected: int
    duplicates_detected: int
    duration_ms: Optional[int]
    trigger_type: str
    triggered_by: Optional[str]
    pipeline_runs: Optional[List[PipelineRunDetail]] = []


class IngestionStatusResponse(BaseModel):
    system_mode: str  # Demo / Live
    scheduler_status: str  # Running / Paused
    last_collection: Optional[str]
    next_collection: Optional[str]
    active_sources: int
    healthy_sources: int
    degraded_sources: int
    active_routes: int
    booking_windows: List[str]
    quotes_today: int
    latest_pipeline_status: str
    latest_apix: float


class DatasetItemResponse(BaseModel):
    id: UUID
    name: str
    dataset_type: str  # live, reference, demo, imported
    source_name: str
    records_count: int
    period: str
    status: str
    created_at: datetime


class DiagnosticsResponse(BaseModel):
    database_connected: bool
    redis_connected: bool
    celery_worker_available: bool
    scheduler_running: bool
    supabase_realtime_configured: bool
    fareguard_loaded: bool
    priceguard_loaded: bool
    apix_engine_ready: bool
    active_collector_count: int
    timestamp: datetime


class SelfTestResult(BaseModel):
    tests_passed: int
    tests_failed: int
    overall_status: str
    test_details: List[Dict[str, Any]]
