import Link from 'next/link';
import { ArrowRight, CalendarDays } from 'lucide-react';
import { Metric, panel, Progress, Status } from './ReadinessUI';

export type APIxReadiness = {
  status: string; required_days: number | null; collected_days: number; remaining_days: number | null;
  history_note: string; eligible_observations: number; eligible_route_count: number; live_days: number; imported_days: number;
  requirements: Record<string,string>;
  base_period: {configured:boolean;start:string|null;end:string|null;available_components:number;required_components:number;status:string};
  distinct_observation_dates: {date:string;observations:number;live_count:number;imported_count:number;routes:string[];windows:string[]}[];
  routes:{route:string;observation_days:number;observations:number;windows:string[];base_status:string}[];
  booking_windows:{window:string;observation_days:number;observations:number;base_status:string}[];
};
export function APIxReadinessDashboard({ data:d }: { data: APIxReadiness }) {
  const days=d.distinct_observation_dates;
  return <div className="space-y-5">
    <section className={`${panel} grid gap-8 lg:grid-cols-2`}>
      <div><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold">APIx Readiness</h2><Status value={d.status}/></div>
        <h3 className="mt-6 text-2xl font-semibold tracking-tight text-slate-900">{d.required_days ? `${d.required_days} days of genuine observation history required` : 'Building an observed reference basket'}</h3>
        <p className="mt-3 max-w-prose text-sm leading-6 text-slate-600">VAYANTARA needs logged, validated fares and matching route/window base references before APIx can be calculated.</p>
        <div className="mt-6 flex items-baseline gap-2"><strong className="text-4xl font-semibold tabular-nums text-blue-700">{d.collected_days}</strong><span className="text-sm text-slate-600">{d.required_days ? `/ ${d.required_days} genuine days collected` : 'genuine observation days collected'}</span></div>
        {d.required_days != null && d.required_days > 0 && <div className="mt-4 space-y-2"><Progress count={d.collected_days} required={d.required_days} label="Observation history"/><p className="text-sm">{d.remaining_days === 0 ? 'History requirement met' : `${d.remaining_days} days remaining`}</p></div>}
        <p className="mt-4 text-xs leading-5 text-slate-600">{d.history_note}</p>
      </div>
      <div className="min-w-0 rounded-lg bg-slate-50 p-5"><h3 className="flex items-center gap-2 font-semibold"><CalendarDays size={18} className="text-blue-600"/>Daily data collection progress</h3><p className="mt-2 text-xs text-slate-600">Actual observation dates (IST), not departure dates. Hover or focus a day for its evidence.</p>
        <div className="mt-6 flex min-h-24 flex-wrap items-end gap-2">{days.map(day=><button type="button" key={day.date} title={`${day.date}: ${day.observations} eligible observations; LIVE ${day.live_count}; IMPORTED ${day.imported_count}; routes ${day.routes.join(', ')}; windows ${day.windows.join(', ')}`} className="h-16 w-9 rounded-t bg-blue-600 text-[10px] text-white hover:bg-blue-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600" aria-label={`${day.date}, ${day.observations} observations`}>{day.date.slice(5)}</button>)}{d.required_days != null && Array.from({length:Math.max(d.required_days-days.length,0)},(_,i)=><span key={`missing-${i}`} title="No eligible observation history recorded" className="h-16 w-9 rounded-t bg-slate-200"/>)}{!days.length && <p className="text-sm text-slate-500">No eligible observation history recorded.</p>}</div>
        <p className="mt-5 text-xs text-slate-600">LIVE: {d.live_days} days · IMPORTED: {d.imported_days} days · Combined: {d.collected_days} distinct days</p><p className="mt-2 text-xs text-slate-500">A date shared by LIVE and IMPORTED counts once.</p>
      </div>
    </section>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Logged Observation Days" value={d.collected_days} detail={d.required_days ? `Out of ${d.required_days} required` : 'Minimum day target not configured'}/><Metric label="Eligible Routes Covered" value={d.eligible_route_count} detail="Routes with eligible basket observations"/><Metric label="Days Remaining" value={d.remaining_days} detail="Requires a configured history target"/><Metric label="Eligible Observations" value={d.eligible_observations} detail="Validated LIVE + IMPORTED fares"/></div>
    <div className="grid gap-5 lg:grid-cols-2"><section className={panel}><h2 className="font-semibold">What is needed to calculate APIx?</h2><div className="mt-4 divide-y divide-slate-100">{[['history','Configured genuine observation history'],['weights','Representative route basket weights'],['base','Matching base-period reference fares'],['current','Validated current route/window observations'],['matched','Matching base and current components']].map(([key,label])=><div key={key} className="flex flex-wrap items-center justify-between gap-2 py-3 text-sm"><span>{label}</span><Status value={d.requirements[key] ?? 'UNAVAILABLE'}/></div>)}</div></section>
    <section className={panel}><h2 className="font-semibold">Base Period Readiness</h2><dl className="mt-5 space-y-4 text-sm">{[['Base period configured',d.base_period.configured?'Yes':'No'],['Base period start',d.base_period.start??'Unavailable'],['Base period end',d.base_period.end??'Unavailable'],['Reference fares available',`${d.base_period.available_components} / ${d.base_period.required_components} route-window components`]].map(([label,value])=><div key={label} className="flex flex-wrap justify-between gap-2"><dt className="text-slate-600">{label}</dt><dd className="font-medium">{value}</dd></div>)}</dl><p className="mt-6 text-xs leading-5 text-slate-500">An analyst must configure the observed base period. More history alone does not create a base basket.</p></section></div>
    <section className={panel}><h2 className="font-semibold">Route coverage</h2><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs text-slate-600"><tr>{['Route','Observation days','Eligible fares','Windows','Base reference'].map(x=><th className="pb-3 pr-4" key={x}>{x}</th>)}</tr></thead><tbody>{d.routes.map(r=><tr key={r.route} className="border-t border-slate-100"><td className="py-4 font-semibold">{r.route}</td><td>{r.observation_days}</td><td>{r.observations}</td><td>{r.windows.join(', ')||'No data'}</td><td><Status value={r.base_status}/></td></tr>)}</tbody></table></div>{!d.routes.length&&<p className="mt-4 text-sm text-slate-500">No configured route weights or eligible observations available.</p>}</section>
    <section className={panel}><h2 className="font-semibold">Booking window coverage</h2><div className="mt-4 flex flex-wrap gap-4">{d.booking_windows.map(w=><div key={w.window} className="min-w-36 rounded-lg bg-slate-50 p-4"><strong>{w.window}</strong><p className="my-2 text-xs text-slate-600">{w.observations} fares · {w.observation_days} days</p><Status value={w.base_status}/></div>)}</div>{!d.booking_windows.length&&<p className="text-sm text-slate-500">Booking-window weights are not configured.</p>}</section>
    <aside className="rounded-xl border border-blue-100 bg-blue-50 p-5"><h2 className="font-semibold text-blue-950">This page will automatically populate</h2><p className="mt-2 text-sm leading-6 text-blue-900">Continue collecting and ingesting genuine fares. Once the configured base and matching observations support a calculation, ingestion can persist APIx and this page will display it automatically.</p><Link href="/scraping-test" className="mt-3 inline-flex items-center gap-2 text-sm font-semibold text-blue-800 hover:underline">Go to Live Scraping <ArrowRight size={16}/></Link></aside>
  </div>;
}
