'use client';
import { useQuery } from '@tanstack/react-query';
import { getData } from '@/lib/api/client';
import { ArrowDown, ShieldCheck } from 'lucide-react';
import { Metric, panel, Progress, ReadinessError, ReadinessSkeleton, Status } from './ReadinessUI';

export type ShockReadiness = {status:string;available_sources:number;required_sources:number;remaining_sources:number;shock_threshold_pct:number;min_quotes:number;min_robust_zscore:number;synchronization_window_minutes:number|null;coverage_period:string;candidate_count:number|null;eligible_routes:number;latest_observed_at:string|null;note:string;sources:{id:string;name:string;latest:string;routes:string[];windows:string[]}[]};
export function PriceShockReadiness() {
  const q=useQuery({queryKey:['price-shock-readiness','real'],queryFn:()=>getData<ShockReadiness>('/alerts/readiness'),refetchInterval:30000});
  if (!q.data) return q.isError ? <ReadinessError title="Unable to load Price Shock verification status" retry={()=>void q.refetch()}/> : <ReadinessSkeleton/>;
  return <>{q.isFetching&&<p role="status" className="text-xs text-blue-700">Refreshing verification state…</p>}{q.isError&&<ReadinessError title="Unable to refresh verification status; showing last received evidence" retry={()=>void q.refetch()}/>}<PriceShockReadinessView data={q.data}/></>;
}
export function PriceShockReadinessView({data:d}:{data:ShockReadiness}) {
  return <div className="space-y-5"><section className={`${panel} grid gap-8 lg:grid-cols-[1.4fr_1fr]`}><div><div className="flex flex-wrap items-center gap-3"><ShieldCheck className="text-blue-600"/><h2 className="text-lg font-semibold">Price Shock Verification Readiness</h2></div><div className="mt-4"><Status value={d.status}/></div><h3 className="mt-5 max-w-2xl text-2xl font-semibold tracking-tight">Independent evidence before market-wide confirmation.</h3><p className="mt-3 text-sm leading-6 text-slate-600">Multiple independent sources must show a comparable, synchronous surge before a route-level movement can be certified as a Price Shock.</p><p className="mt-4 text-xs text-slate-500">Coverage period: {d.coverage_period}</p></div><div className="rounded-lg bg-slate-50 p-5"><h3 className="text-sm font-semibold">Independent source coverage</h3><p className="my-5"><strong className="text-4xl font-semibold tabular-nums text-blue-700">{d.available_sources}</strong><span className="ml-2 text-slate-600">/ {d.required_sources} required</span></p><Progress count={d.available_sources} required={d.required_sources} label="Independent sources"/><p className="mt-3 text-sm text-slate-600">{d.remaining_sources ? `${d.remaining_sources} more independent sources required` : 'Source count reached; event verification still required'}</p><p className="mt-5 text-xs text-slate-500">Latest eligible observation: {d.latest_observed_at??'None recorded in this period'}</p></div></section>
    <div className="grid gap-4 sm:grid-cols-3"><Metric label="Independent Sources" value={`${d.available_sources} / ${d.required_sources}`} detail="Distinct live collection channels"/><Metric label="Observed Corridors" value={d.eligible_routes} detail="Coverage does not establish comparability"/><Metric label="Candidate Surges" value={d.candidate_count} detail="Candidate evaluations are not currently persisted"/></div>
    <div className="grid gap-5 lg:grid-cols-2"><section className={panel}><h2 className="font-semibold">What is required to confirm a Price Shock?</h2><ul className="mt-4 divide-y divide-slate-100 text-sm">{[`At least ${d.required_sources} independent sources`, `At least ${d.min_quotes} observed quotes`, `Fare increase of at least ${d.shock_threshold_pct}%`, `Robust Z-score of at least ${d.min_robust_zscore}`, 'Comparable route and booking-window evidence', d.synchronization_window_minutes==null?'Event synchronization timing: unavailable':`Synchronous evidence within ${d.synchronization_window_minutes} minutes`, 'Validated LIVE provenance and active confirmation'].map(x=><li key={x} className="py-3 text-slate-700">{x}</li>)}</ul></section>
    <section className={panel}><h2 className="font-semibold">Multi-source verification pipeline</h2><p className="mt-2 text-xs text-slate-500">Coverage is available below. Event-level steps remain unverified until recorded by the backend.</p><ol className="mt-4 space-y-2">{['Observed fare surge','Route / window alignment','Source independence check','Temporal synchronization','Threshold verification','Confirmed Price Shock'].map((x,i)=><li key={x}><div className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-slate-50 p-3 text-sm"><span>{x}</span><Status value={i===2?d.status:'UNAVAILABLE'}/></div>{i<5&&<ArrowDown aria-hidden="true" size={14} className="mx-auto mt-2 text-slate-400"/>}</li>)}</ol></section></div>
    <section className={panel}><h2 className="font-semibold">Source Verification Coverage</h2><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs text-slate-600"><tr>{['Source','Latest observation','Routes','Windows'].map(x=><th key={x} className="pb-3 pr-5">{x}</th>)}</tr></thead><tbody>{d.sources.map(s=><tr key={s.id} className="border-t border-slate-100"><td className="py-4 pr-5 font-semibold">{s.name}</td><td className="pr-5">{s.latest}</td><td className="pr-5">{s.routes.join(', ')}</td><td>{s.windows.join(', ')}</td></tr>)}</tbody></table></div>{!d.sources.length&&<p className="mt-3 text-sm text-slate-500">No eligible LIVE source observations in this coverage period.</p>}</section>
    <section className={panel}><div className="flex flex-wrap items-center gap-3"><h2 className="font-semibold">Unverified Surge Candidates</h2><Status value="UNAVAILABLE"/></div><p className="mt-3 text-sm leading-6 text-slate-600">Candidate evaluations are not currently exposed by the backend. Anomaly records are not treated as surge candidates or confirmed shocks.</p></section>
    <aside className="rounded-xl border border-blue-100 bg-blue-50 p-5 text-sm leading-6 text-blue-950"><h2 className="font-semibold">Why source coverage matters</h2><p className="mt-2">{d.note}</p><p className="mt-2">Repeated collections from one source improve history, but do not add independent confirmation channels. Global coverage does not prove agreement on the same route or booking window.</p></aside>
  </div>;
}
